name: Benchmark
on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          dependency-graph: generate-and-submit

      - name: Cache konan dependencies
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and run JMH benchmarks
        run: |
          # Clean to ensure a fresh build
          ./gradlew clean benchmarks:benchmark

      - name: JMH Benchmark Action
        uses: kitlangton/jmh-benchmark-action@main
        with:
          jmh-output-path: benchmarks/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-regression: true